### ISSUE TITLE
Please remove me and the rest of the people from "Contributing" section

### ISSUE THREAD

**Issue by ku3o** [ciso112/kiwi-currencies#8]
Although it's nice that you consider us as contributors, we haven't done a single commit :).  This is your project. Please remove us from `Contributing` section in `README.md`.

```
Contributing
MichalCab, vorelq, valfa14, lrn86, ku3o, lbenka, cernekm
```

**Comment by ciso112** [comment]
Sorry for inconvenience, to state you as contributors was a part of an assignment, that's why..
